In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt

In [9]:
Thermal=pd.read_csv(r'D:\Python\Thermal_AR.csv')
Wind=pd.read_csv(r'D:\Python\Windpower_AR.csv')

In [10]:
Thermal

,Technology,Power Plant Name,Fuel Category,Primary Fuel,Region,Country,Total Capacity (MW),Active Capacity (MW),Pipeline Capacity (MW),Discontinued Capacity (MW),Status,Owner Name,Owner Stake (%)
0,Thermal,46864175ac power plant,Gas,Natural Gas,Europe,Romania,774.3000,774.300,NaN,NaN,Active,Acme Oil & Gas Corporation,NaN
1,Thermal,e73ddc5a12 power plant,Gas,Natural Gas,Middle East and Africa,Iran (Islamic Republic of Iran),679.1800,679.180,NaN,NaN,Active,Acme Oil & Gas Corporation,NaN
2,Thermal,08e7c3d6f3 power plant,Gas,Natural Gas,South and Central America,Argentina,801.8500,NaN,NaN,NaN,Active,Acme Oil & Gas Corporation,NaN
3,Thermal,da41646568 power plant,Oil,Distillate Fuel Oil,North America,United States,4.4000,NaN,NaN,NaN,Active,Acme Oil & Gas Corporation,100.0
4,Thermal,bf830a8e26 power plant,Oil,Distillate Fuel Oil,North America,United States,3.7800,NaN,NaN,NaN,Active,Acme Oil & Gas Corporation,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
775,Thermal,8cb7cbd82f power plant,Coal,Coal,Asia-Pacific,India,844.8000,NaN,NaN,NaN,Suspended,Wonka Energy LTD,NaN
776,Thermal,c5e8f044a4 power plant,Gas,Gas,Europe,Germany,0.2450,0.245,NaN,NaN,Active,Wonka Energy LTD,NaN
777,Thermal,e9ea6f035d power plant,Coal,Anthracite,Asia-Pacific,China,235.0000,NaN,NaN,NaN,Active,Wonka Energy LTD,100.0
778,Thermal,178afe167f,Coal,Coal,Asia-Pacific,China,2460.0000,NaN,NaN,NaN,Dormant,Wonka Energy LTD,NaN
779,Thermal,7e5ee14d10 plant,Gas,Natural Gas,Europe,Spain,15.1227,NaN,NaN,15.1227,Decommissioned,Wonka Energy LTD,100.0

In [11]:
Thermal.describe()

,Total Capacity (MW),Active Capacity (MW),Pipeline Capacity (MW),Discontinued Capacity (MW),Owner Stake (%)
count,710.000000,363.000000,81.000000,42.000000,445.000000
mean,338.067555,96.557620,389.148570,379.687803,91.059326
std,735.656769,225.705567,502.123991,555.558989,22.884334
min,0.003660,0.003660,0.211600,0.006900,0.100000
25%,4.828350,1.321000,43.800000,16.931250,100.000000
50%,51.543600,11.680000,196.200000,115.100000,100.000000
75%,339.450000,67.920000,569.430000,504.822500,100.000000
max,7384.000000,1862.500000,2356.200000,2016.000000,100.000000

In [12]:
Thermal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 780 entries, 0 to 779
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Technology                  780 non-null    object
 1   Power Plant Name            779 non-null    object
 2   Fuel Category               779 non-null    object
 3   Primary Fuel                779 non-null    object
 4   Region                      779 non-null    object
 5   Country                     779 non-null    object
 6   Total Capacity (MW)         710 non-null    float64
 7   Active Capacity (MW)        363 non-null    float64
 8   Pipeline Capacity (MW)      81 non-null     float64
 9   Discontinued Capacity (MW)  42 non-null     float64
 10  Status                      779 non-null    object
 11  Owner Name                  779 non-null    object
 12  Owner Stake (%)             445 non-null    float64
dtypes: float64(5), object(8)
memory usage: 79.3+ KB

In [15]:
Thermal['Owner Name'].value_counts()

LexCorp Energy Enterprises    269
Stark Energy Corporation      140
Dynamis Corporation           133
Acme Oil & Gas Corporation    124
Wonka Energy LTD              113
Name: Owner Name, dtype: int64